# Generated by Django 3.0.4 on 2022-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_header', models.CharField(max_length=100, unique=True)),
                ('alarm_content', models.CharField(max_length=400)),
                ('alarm_date', models.DateTimeField()),
            ],
        ),
    ]
