# Generated by Django 3.0.4 on 2022-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_header', models.CharField(max_length=100, unique=True)),
                ('notifications_content', models.TextField()),
                ('notifications_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_content',
            field=models.TextField(),
        ),
    ]
