# Generated by Django 3.0.4 on 2022-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_auto_20220605_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='icon_tag',
            field=models.CharField(blank=True, default='fa-bell', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='icon_tag',
            field=models.CharField(blank=True, default='fa-envelope', max_length=50, null=True),
        ),
    ]
