# Generated by Django 3.0.4 on 2022-06-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_auto_20220605_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('-date',)},
        ),
    ]
