# Generated by Django 3.0.4 on 2022-05-18 12:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(default='defaultplayer.jpg', upload_to='profile_pics')),
                ('playingRole', models.CharField(choices=[('Captain', 'Captain'), ('GoalKeeper', 'GoalKeeper'), ('Player', 'Player')], max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Fantasy.FootballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('team1_goals', models.IntegerField(blank=True, null=True)),
                ('team2_goals', models.IntegerField(blank=True, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='Fantasy.FootballTeam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='Fantasy.FootballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=False)),
                ('goal', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('own_goal', models.IntegerField(default=0)),
                ('yellow_card', models.BooleanField(default=False)),
                ('red_card', models.BooleanField(default=False)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('penalty_saved', models.IntegerField(default=0)),
                ('penalty_missed', models.IntegerField(default=0)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Fantasy.Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='Fantasy.Player')),
            ],
            options={
                'unique_together': {('player', 'fixture')},
            },
        ),
        migrations.CreateModel(
            name='FantasySquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('captainSelected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C', to='Fantasy.Player', verbose_name='Captain')),
                ('goalKeeperSelected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GK', to='Fantasy.Player', verbose_name='GoalKeeper')),
                ('player1Selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P1', to='Fantasy.Player', verbose_name='Player 1')),
                ('player2Selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P2', to='Fantasy.Player', verbose_name='Player 2')),
                ('player3Selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P3', to='Fantasy.Player', verbose_name='Player 3')),
                ('player4Selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P4', to='Fantasy.Player', verbose_name='Player 4')),
                ('player5Selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P5', to='Fantasy.Player', verbose_name='Player 5')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='Fantasy.Team')),
            ],
            options={
                'unique_together': {('team', 'gameweek')},
            },
        ),
    ]
