# Generated by Django 3.0.4 on 2022-05-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='team1_goals',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='team2_goals',
        ),
    ]
