# Generated by Django 3.0.4 on 2020-03-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasysquad',
            name='player4Selected',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='player5Selected',
        ),
    ]
