# Generated by Django 3.0.4 on 2022-05-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0002_auto_20220518_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['gameweek', 'date']},
        ),
    ]
