# Generated by Django 3.0.4 on 2020-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0002_auto_20200313_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasysquad',
            old_name='captinSelected',
            new_name='captainSelected',
        ),
        migrations.AlterField(
            model_name='player',
            name='playingRole',
            field=models.CharField(choices=[('Captain', 'Captain'), ('GoalKeeper', 'GoalKeeper'), ('Player', 'Player')], max_length=100),
        ),
    ]
