# Generated by Django 3.0.4 on 2020-03-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0002_auto_20200308_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasysquad',
            name='captinSelected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='C', to='Fantasy.Player'),
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='goalKeeperSelected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GK', to='Fantasy.Player'),
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='player2Selected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P2', to='Fantasy.Player'),
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='player3Selected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P3', to='Fantasy.Player'),
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='players1Selected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P1', to='Fantasy.Player'),
        ),
    ]
