# Generated by Django 3.0.4 on 2020-03-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0003_auto_20200313_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fantasysquad',
            unique_together={('team', 'gameweek')},
        ),
    ]
