# Generated by Django 3.0.4 on 2022-05-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0003_auto_20220518_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('gameweek', 'team1', 'team2')},
        ),
    ]
