# Generated by Django 3.0.4 on 2020-03-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0003_auto_20200308_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasysquad',
            name='captinSelected',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='goalKeeperSelected',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='lastRoundScore',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='overallScore',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='player2Selected',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='player3Selected',
        ),
        migrations.RemoveField(
            model_name='fantasysquad',
            name='players1Selected',
        ),
    ]
