# Generated by Django 3.0.4 on 2020-03-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0004_auto_20200308_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasysquad',
            name='captinSelected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='C', to='Fantasy.Player'),
        ),
    ]
