# Generated by Django 3.0.4 on 2022-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0004_auto_20220518_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameweekSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_gameweek', models.IntegerField()),
                ('gameweek_deadline', models.DateTimeField()),
            ],
        ),
    ]
