# Generated by Django 3.0.4 on 2020-03-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0004_auto_20200313_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.BooleanField(default=False)),
                ('red_cards', models.BooleanField(default=False)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('penalty_saved', models.IntegerField(default=0)),
                ('penalty_missed', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='Fantasy.Player')),
            ],
            options={
                'unique_together': {('player', 'gameweek')},
            },
        ),
    ]
