# Generated by Django 3.0.4 on 2020-03-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0005_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='assists',
            new_name='assist',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='goals',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='red_cards',
            new_name='red_card',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='yellow_cards',
            new_name='yellow_card',
        ),
    ]
