# Generated by Django 3.0.4 on 2022-05-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0005_gameweeksetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='stage',
            field=models.CharField(choices=[('G', 'Group'), ('QF', 'Quarter-Final'), ('SF', 'Semi-Final'), ('3P', '3rd Place Playoff'), ('F', 'Final')], default='G', max_length=20),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1_representation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2_representation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='Fantasy.FootballTeam'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='Fantasy.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Fantasy.Group'),
        ),
    ]
