# Generated by Django 3.0.4 on 2022-05-05 15:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Fantasy', '0006_auto_20200313_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='Fantasy.Team'),
        ),
        migrations.DeleteModel(
            name='FantasyTeam',
        ),
    ]
