# Generated by Django 3.0.4 on 2022-05-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0006_auto_20220526_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('playerName',)},
        ),
    ]
