# Generated by Django 3.0.4 on 2022-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0007_auto_20220527_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballteam',
            name='color',
            field=models.CharField(default='royalblue', max_length=20),
        ),
    ]
