# Generated by Django 3.0.4 on 2022-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0008_footballteam_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_header', models.CharField(max_length=100, unique=True)),
                ('alarm_content', models.CharField(max_length=400, unique=True)),
                ('alarm_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_header', models.CharField(max_length=100, unique=True)),
                ('message_content', models.CharField(max_length=400, unique=True)),
                ('message_date', models.DateTimeField()),
            ],
        ),
    ]
