# Generated by Django 3.0.4 on 2022-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0008_footballteam_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
