# Generated by Django 3.0.4 on 2022-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0009_alarm_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(max_length=400),
        ),
    ]
