# Generated by Django 3.0.4 on 2022-06-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0010_auto_20220604_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message_content',
            new_name='messages_content',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message_date',
            new_name='messages_date',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='message_header',
            new_name='messages_header',
        ),
    ]
