# Generated by Django 3.0.4 on 2022-06-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0011_auto_20220604_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
