# Generated by Django 3.0.4 on 2022-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0009_fixture_url'),
        ('Fantasy', '0012_auto_20220604_1311'),
    ]

    operations = [
    ]
