# Generated by Django 3.0.4 on 2022-06-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0013_merge_20220606_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='withdrawn_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_fixtures', to='Fantasy.FootballTeam'),
        ),
    ]
