# Generated by Django 3.0.4 on 2022-06-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0014_fixture_withdrawn_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='withdrawn_team',
            field=models.ForeignKey(blank=True, help_text='If one of the teams withdrew from the match, select it and the other team will be considered as the winner of the match with score 2-0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_fixtures', to='Fantasy.FootballTeam'),
        ),
    ]
