# Generated by Django 4.0.5 on 2022-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0015_auto_20220628_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweeksetting',
            name='max_players_same_team',
            field=models.IntegerField(default=2),
        ),
    ]
