# Generated by Django 4.0.5 on 2022-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantasy', '0016_gameweeksetting_max_players_same_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='team1_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
